// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using PipboyOrganizer.Models;
using UIKit;

namespace PipboyOrganizer
{
    public partial class AddQuestViewController : UIViewController,IUITableViewDelegate, IUITableViewDataSource
	{
        List<Stage> stages = new List<Stage>();

		public AddQuestViewController (IntPtr handle) : base (handle)
		{
            
		}

        public UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
        {
            var cell = tableView.DequeueReusableCell("StageViewCell", indexPath)as StageViewCell;
            cell.StageDescription = stages[indexPath.Row].Description;
            return cell;
        }

        public nint RowsInSection(UITableView tableView, nint section)
        {
            return stages.Count;
        }
        private void AddStage()
        {
            InvokeOnMainThread(() =>
            {
                Stage stage = new Stage();
                stage.Description = TxtQuestStage.Text;
                stage.isCompleted = false;
                stages.Add(stage);

                tblStages.ReloadData();
            });
                 
           // NSIndexPath indexPath = NSIndexPath.FromRowSection(stages.Count - 1, 0);

            //tblStages.InsertRows(indexPath,UITableViewRowAnimation.Automatic);
        }
		partial void BtnAddStageTouchUpInside(NSObject sender)
		{
            
            AddStage();
		}

	}
}
