// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace PipboyOrganizer
{
	public partial class InsideTableViewCell : UITableViewCell
	{
        public String Task
        {
            get => LblTask.Text;
            set => LblTask.Text = value;
        }
		public InsideTableViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
