// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace PipboyOrganizer
{
	public partial class MainTableViewCell : UITableViewCell
	{
        public String QuestName
        {
            get=>LblQuestName.Text;
            set=> LblQuestName.Text = value;
        }
        public String QuestDescription
        {
            get => LblQuestDescription.Text;
            set => LblQuestDescription.Text = value;
        }
		public String LastStage {
			get => LblLastStage.Text;
			set => LblLastStage.Text = value;
		}

        public UITableView TableViewInside
        {
            get => TblInside;
            set => TblInside = value;
        }
        public MainTableViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
