// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using PipboyOrganizer.Models;
namespace PipboyOrganizer
{
	public partial class QuestInfoViewController : UIViewController ,IUITableViewDelegate,IUITableViewDataSource
	{
		public Quest selectedQuest;

		public QuestInfoViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			LblTitle.Text = selectedQuest.Name;
			LblDescription.Text= selectedQuest.Description;
			tblStages.DataSource = this;
			tblStages.Delegate = this;

		}



		public nint RowsInSection (UITableView tableView, nint section)
		{
			return selectedQuest?.QuestStages == null ? 0 : selectedQuest.QuestStages.Count;
		}
		public UITableViewCell GetCell (UITableView tableView, NSIndexPath indexPath)
		{
			var cell = tableView.DequeueReusableCell ("StageViewCell", indexPath) as StageViewCell;
			cell.StageDescription = selectedQuest.QuestStages[indexPath.Row].Description;
			return cell;
		}

	}
}
