// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Firebase.Database;
using Foundation;
using PipboyOrganizer.Models;
using UIKit;

namespace PipboyOrganizer {
	public partial class QuestViewController : UIViewController, IUITableViewDelegate, IUITableViewDataSource {
		public int c = 0;

		public QuestViewController (IntPtr handle) : base (handle)
		{

		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

		}

		public override void PrepareForSegue (UIStoryboardSegue segue, NSObject sender)
		{
			
			if (segue.Identifier == "QuestDetail") {
				var indexPath = tblQuests.IndexPathForSelectedRow;
				var vc = segue.DestinationViewController as QuestInfoViewController;
				vc.selectedQuest = UserPersistanceClass.myUser.ActiveQuests [indexPath.Row];
				PerformSegue ("QuestDetail", sender);
			}
		}


		public UITableViewCell GetCell (UITableView tableView, NSIndexPath indexPath)
		{
			//try
			//{
			//    for (int i = 0; i < UserPersistanceClass.myUser.ActiveQuests.Count; i++)
			//    {
			//        Quest quest = UserPersistanceClass.myUser.ActiveQuests[i];
			//        //Quest
			//        if (tableView.Tag == 10)
			//        {
			//            var cell = tableView.DequeueReusableCell("MainTableViewCell", indexPath) as MainTableViewCell;
			//            cell.QuestName = quest.Name;
			//            cell.QuestDescription = quest.Description;
			//            tableView.RowHeight = 400;
			//            return cell;
			//        }
			//        for (int k = 0; k < quest.QuestStages.Count; k++)
			//        {
			//            //Stages
			//            if (tableView.Tag == 20)
			//            {
			//                var cell = tableView.DequeueReusableCell("InsideTableViewCell", indexPath) as InsideTableViewCell;
			//                cell.Task = quest.QuestStages[k].Description;
			//                tableView.RowHeight = 100;
			//                tableView.EstimatedRowHeight = 50;
			//                return cell;
			//            }
			//        }
			//    }
			//}
			//catch (Exception ex)
			//{
			//    throw ex;
			//}

			var cell = tableView.DequeueReusableCell ("MainTableViewCell", indexPath) as MainTableViewCell;
			cell.QuestName = UserPersistanceClass.myUser.ActiveQuests [indexPath.Row].Name;
			cell.QuestDescription = UserPersistanceClass.myUser.ActiveQuests [indexPath.Row].Description;

			foreach (var stage in UserPersistanceClass.myUser.ActiveQuests [indexPath.Row].QuestStages) {
				if (!stage.isCompleted) {
					cell.LastStage = stage.Description;
				}
			}

			tableView.RowHeight = 100;
			tableView.EstimatedRowHeight = 50;
			return cell;


		}
		public override void PerformSegue (string identifier, NSObject sender)
		{
			
				
		}

		public nint RowsInSection (UITableView tableView, nint section)
		{
			return 1;
		}



	}
}
