// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace PipboyOrganizer
{
	public partial class ScheduleViewController : UIViewController
	{
		public ScheduleViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
