// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace PipboyOrganizer
{
	public partial class SkillViewCell : UICollectionViewCell
	{
        public string Name
        {
            get=> LblSkillName.Text;
            set=> LblSkillName.Text = value;
        }
        public string SkillDescription
        {
            get => LblDescription.Text;
            set => LblDescription.Text = value;
        }

        public string Level
        {
            get => LblSkillLevel.Text;
            set => LblSkillLevel.Text = value;
        }
        public SkillViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
