// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace PipboyOrganizer
{
	public partial class SkillViewCell : UICollectionViewCell
	{
		public SkillViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
