// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace PipboyOrganizer
{
	public partial class StageViewCell : UITableViewCell
	{
        public String StageDescription
        {
            get => LblStageDescription.Text;
            set => LblStageDescription.Text = value;
        }
		public StageViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
